#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new \Systatiko\Console\GeneratorCommand('generate'));
$app->run();